### PR TITLE
Map work - create service for Trees and TreeIcons

### PR DESCRIPTION
**Pull request by jalal**
* Pulled Axios and Leaflet libraries to use the NPM system.
* Separated out the OpenDataBristol API connection in to a Trees.service
* Pull in icons from a TreeIcon service. For now, I've used a FlatIcon set of SVG icons for the maps. We can change that out later.
* Added a loading spinner
* Added a simple logger library to handle console log messages.
* Create a config file for app configuration, and http utility file.

### CODE REVIEW

**Comment by joshJarr** [comment]
Looks good! I’ll give this a proper review when I’m back on the 30th 👍🏻

**Comment by tomwieck** [comment]
This is looking really good, nice work! Made a few small changes, feel free to revert or modify anything if you think it's needed. Once Josh has had a look happy for this to be merged, then think it would be good to refactor some of the fetching stuff to use our server code once were confident it will work.

**Comment by joshJarr** [comment]
Sorry for the delay! looks good, a few nits that I'll push now.
One issue I'm finding is the performance of the map widget is a little slow - when interacting with/clicking sometimes by browser freezes! I'll investigate, could be related to leaflet?

**Comment by joshJarr** [comment]
Ahh ok, interesting. I did find this https://github.com/Leaflet/Leaflet.VectorGrid - apparently could help? Something worth investigating further.
I'll merge this and create a new issue, as I'm happy how this is working right now 👍 
issue here: https://github.com/tomwieck/triffid/projects/1

**Comment by tomwieck** [comment]
Couldnt see a way to add comments to the issue above, but found this which looks helpful too! https://stackoverflow.com/questions/43015854/large-dataset-of-markers-or-dots-in-leaflet

**Pull request merged**
